const halloffamedata = [
  {
    player: "Boysie",
    id: 224,
    lines: 2,
    green: 8,
    yellow: 0,
    word: "COULD",
  },
  {
    player: "Sunny",
    id: 227,
    lines: 2,
    green: 6,
    yellow: 2,
    word: "THOSE",
  },
  {
    player: "Lee",
    id: 227,
    lines: 2,
    green: 6,
    yellow: 2,
    word: "THOSE",
  },
  {
    player: "Boysie",
    id: 228,
    lines: 2,
    green: 7,
    yellow: 2,
    word: "MOIST",
  },
  {
    player: "Geoff",
    id: 228,
    lines: 2,
    green: 6,
    yellow: 2,
    word: "MOIST",
  },
  {
    player: "Geoff",
    id: 230,
    lines: 2,
    green: 7,
    yellow: 1,
    word: "PLEAT",
  },
  {
    player: "Lloydy",
    id: 235,
    lines: 2,
    green: 6,
    yellow: 2,
    word: "HUMOR",
  },
  {
    player: "Sunny",
    id: 238,
    lines: 2,
    green: 5,
    yellow: 3,
    word: "ULTRA",
  },
  {
    player: "Aaron",
    id: 238,
    lines: 2,
    green: 5,
    yellow: 3,
    word: "ULTRA",
  },
  {
    player: "Robbie",
    id: 243,
    lines: 2,
    green: 5,
    yellow: 2,
    word: "SHAKE",
  },
  {
    player: "Stevie",
    id: 245,
    lines: 2,
    green: 5,
    yellow: 3,
    word: "SHILL",
  },
  {
    player: "Lee",
    id: 247,
    lines: 2,
    green: 6,
    yellow: 2,
    word: "OTHER",
  },
  {
    player: "Lloydy",
    id: 247,
    lines: 2,
    green: 8,
    yellow: 1,
    word: "OTHER",
  },
  {
    player: "Sunny",
    id: 247,
    lines: 2,
    green: 7,
    yellow: 1,
    word: "OTHER",
  },
  {
    player: "Stevie",
    id: 248,
    lines: 2,
    green: 7,
    word: "THORN",
  },
  {
    player: "Robbie",
    id: 250,
    lines: 2,
    green: 6,
    yellow: 1,
    word: "BLOKE",
  },
  {
    player: "Robbie",
    id: 254,
    lines: 2,
    green: 7,
    yellow: 0,
    word: "CHOKE",
  },
  {
    player: "Boysie",
    id: 256,
    lines: 2,
    green: 6,
    yellow: 3,
    word: "NASTY",
  },
  {
    player: "Aaron",
    id: 256,
    lines: 2,
    green: 5,
    yellow: 4,
    word: "NASTY",
  },
  {
    player: "Sunny",
    id: 257,
    lines: 2,
    green: 7,
    yellow: 2,
    word: "MOURN",
  },
  {
    player: "Aaron",
    id: 259,
    lines: 2,
    green: 5,
    yellow: 2,
    word: "BRINE",
  },
];
