const halloffamedata = [
  {
    player: "Boysie",
    id: 224,
    lines: 2,
    green: 8,
    yellow: 0,
    blank: 2,
    word: "COULD",
  },
  {
    player: "Sunny",
    id: 227,
    lines: 2,
    green: 6,
    yellow: 2,
    blank: 2,
    word: "THOSE",
  },
  {
    player: "Lee",
    id: 227,
    lines: 2,
    green: 6,
    yellow: 2,
    blank: 2,
    word: "THOSE",
  },
  {
    player: "Boysie",
    id: 228,
    lines: 2,
    green: 7,
    yellow: 2,
    blank: 1,
    word: "MOIST",
  },
//  {
//    player: "Geoff",
//    id: 228,
//    lines: 2,
//    green: 6,
//    yellow: 2,
//    blank: 2,
//    word: "MOIST",
//  },
//  {
//    player: "Geoff",
//    id: 230,
//    lines: 2,
//    green: 7,
//    yellow: 1,
//    blank: 2,
//    word: "PLEAT",
//  },
//  {
//    player: "Lloydy",
//    id: 235,
//    lines: 2,
//    green: 6,
//    yellow: 2,
//    blank: 2,
//    word: "HUMOR",
//  },
  {
    player: "Sunny",
    id: 238,
    lines: 2,
    green: 5,
    yellow: 3,
    blank: 2,
    word: "ULTRA",
  },
  {
    player: "Aaron",
    id: 238,
    lines: 2,
    green: 5,
    yellow: 3,
    blank: 2,
    word: "ULTRA",
  },
];
